googleapis/google-resumable-media-python

gooresmed/upload.py, tests/system/test_upload.py, tests/unit/test_upload.py
This way an instance can be marked when an unexpected response occurs.
=> Add ResumableUpload.invalid().

google/resumable_media/__init__.py, google/resumable_media/_helpers.py, tests/unit/test__helpers.py, tests/unit/test_upload.py
Will always retry on 429, 500, 502, 503 and 504. Based on:
https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#handling_errors
=> Adding retries for **ANY** http request.

docs_build/custom_html_writer.py
I am going to auto-merge before CI finishes (I know this works because I had to make the same fix in [`bezier`][1])
[1]: https://github.com/dhermes/bezier
=> Updating custom_html_writer after Sphinx update removed a class.

MANIFEST.in
Fixes #8.
/cc @johanneskoester
@jonparrott I mostly just copy-pasted the `MANIFEST.in` from Datastore. As a result I am somewhat unsure, so can you "scrutinize"?
=> Adding MANIFEST.in to repository.

google/resumable_media/_upload.py, tests/unit/test__upload.py
Fixes #12.
After merging a micro release should go out.
=> Making sure we pass unicode to `json.loads()` rather than `bytes`.

google/resumable_media/_upload.py, tests/unit/test__upload.py
(This is in keeping with all string literals in tests and source code.)
=> Using explicit u prefix on unicode string.

google/resumable_media/_upload.py, google/resumable_media/requests/upload.py, nox.py, tests/unit/test__upload.py
Also made some tweaks in `nox.py` to allow passing through positional args, e.g.
```
nox -s "unit_tests(python_version='3.6')" -r -- --pdb
```
/cc @tseaver 
This is **required** (with a release) to finish https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3555. As I [stated][1] there, I made a bad assumption that `size` would always be in the 200 response when a resumable upload is concluded.
----
For "inspection", compare a Storage response
```json
{
"bucket": "{BUCKET}",
"contentType": "text/plain",
"crc32c": "MR/5OA==",
"etag": "CMm6nMn0mNUCEAE=",
"generation": "1500589786078537",
"id": "{BUCKET}/{FILENAME}.txt/1500589786078537",
"kind": "storage#object",
"md5Hash": "vl1dN1Qtdfk6hwlEWfdmeA==",
"mediaLink": "https://www.googleapis.com/download/storage/v1/b/{BUCKET}/o/{FILENA …
```
=> Dropping usage of "size" to measure (resumable) bytes uploaded.

google/resumable_media/requests/download.py
Since this doesn't actually change the interface, none of the docs for `latest/` or `0.2.2/` need be changed.
Once merged, I propose this commit be tagged as the NEW-AND-IMPROVED `0.2.2` release
/cc @tseaver
=> Swap the order of _write_to_stream() / _process_response() in `requests` download.

google/resumable_media/_upload.py, tests/unit/test__upload.py
@dhermes I am not sure this is actually the correct fix for GoogleCloudPlatform/google-cloud-python#3685, but it _seems_ logical and in line with what the original reporter expected.
If this is the wrong answer, I would appreciate guidance on what the correct answer is.
Fixes GoogleCloudPlatform/google-cloud-python#3685
=> Allow empty files to be uploaded.

google/resumable_media/requests/download.py, nox.py, tests/system/requests/test_download.py, tests/unit/requests/test_download.py
Fixes #34.
/cc @tseaver @mfschwartz
@jonparrott Do you think we should cc the `requests` / `urllib3` maintainers? I'm also working on a PR to fix the failing system test, but it is **not** going to be part of this PR.
=> Add requests/urllib3 work-around for intercepting gzipped bytes.

.appveyor.yml, appveyor/env_info.py, appveyor/requirements.txt, google/resumable_media/_upload.py
I'm doing this in **anticipation** of adding CRCMOD support (i.e. a C dependency).
We want to know that the extension can build on Windows and likely want to just get wheels directly from the builds.
=> Adding AppVeyor support.

google/resumable_media/requests/__init__.py
See #42 and #43.
/cc @brandonw @mlissner @tseaver
=> Making `requests` a strict dependency for the `requests` subpackage.

.circleci/config.yml, noxfile.py
=> Update to new nox

noxfile.py, tests/system/requests/conftest.py, tests/system/requests/test_download.py, tests/system/requests/test_upload.py, tests/system/utils.py
=> Fix systest bitrot.

google/resumable_media/requests/__init__.py
Supersedes PR #70.
Closes #58.
=> DRY 'requests' pin; don't shadow exception.

docs/latest/.buildinfo, google/resumable_media/requests/_helpers.py, tests/unit/requests/test__helpers.py, tests/unit/requests/test_download.py, tests/unit/requests/test_upload.py
Related to https://github.com/googleapis/google-cloud-python/issues/5909 and https://github.com/googleapis/google-cloud-python/issues/8571 and https://github.com/cshesse/blobfile/issues/2 and https://github.com/googleapis/google-resumable-media-python/issues/45
Timeout selected to be in line with gsutil.
https://github.com/GoogleCloudPlatform/gsutil/blob/0d9d0175b2b10430471c7b744646e56210f991d3/gslib/utils/constants.py#L89
=> Add a default timeout for the http_request method

.flake8, google/resumable_media/__init__.py, google/resumable_media/_download.py, google/resumable_media/_helpers.py, google/resumable_media/_upload.py, google/resumable_media/common.py, google/resumable_media/requests/__init__.py, google/resumable_media/requests/_helpers.py, google/resumable_media/requests/download.py, google/resumable_media/requests/upload.py, noxfile.py, synth.py, tests/system/requests/conftest.py, tests/system/requests/test_download.py, tests/system/requests/test_upload.py, tests/system/utils.py, tests/unit/requests/test__helpers.py, tests/unit/requests/test_download.py, tests/unit/requests/test_upload.py, tests/unit/test__download.py, tests/unit/test__helpers.py, tests/unit/test__upload.py, tests/unit/test_common.py
Adds a nox session `black`.  Also adds a synth script to copy templates for kokoro jobs.
=> Add black.

docs/latest/.buildinfo, google/resumable_media/_download.py, google/resumable_media/requests/_helpers.py, google/resumable_media/requests/download.py, noxfile.py, tests/system/requests/test_download.py, tests/unit/requests/test__helpers.py, tests/unit/requests/test_download.py, tests/unit/test__download.py
This reverts commit 2b9ffc813b47912b5609985db9dc5d9e4936310a.
This library is being used by google-cloud-storage with only a >= specifier. This change caused breakages in all existing clients.
=> Revert "Always use raw response data. (#87)"

google/__init__.py, google/resumable_media/_download.py, google/resumable_media/requests/__init__.py, google/resumable_media/requests/_helpers.py, google/resumable_media/requests/download.py, google/resumable_media/requests/upload.py, tests/system/requests/test_download.py, tests/system/requests/test_upload.py, tests/unit/requests/test__helpers.py, tests/unit/requests/test_download.py, tests/unit/requests/test_upload.py, tests/unit/test__download.py, tests/unit/test__helpers.py, tests/unit/test__upload.py
Restores "raw download" behavior as separate `RawDownload` and `RawChunkedDownload` classes:  the existing `Download` and `ChunkedDownload` classes retain their bad-but-backward-compatible behavior of expanding resources with `Content-Encoding` headers set.
Closes #106.
=> feat: add raw download classes

setup.py
Internal tools depend on reconciling the PyPI package metadata with the .repo-metadata.json in the repository. This PR corrects the URL in setup.py
=> docs: corrects repo url in package metadata

.repo-metadata.json
Is this right? I was having trouble finding the docs on googleapis.dev, wondering if this got missed in the transition?
=> chore: update client_documentation link

google/resumable_media/_upload.py, tests/unit/test__upload.py
=> fix: accept `201 Created` as valid upload response

noxfile.py, tests/system/requests/conftest.py, tests/system/requests/test_upload.py, tests/system/utils.py
=> testing: harden systest teardowns vs transient GCS errors

setup.py
/cc @tswast
Prepare for upcoming version, which will namespace the module to avoid
conflict with the ICRAR version.
See: https://github.com/googleapis/python-crc32c/issues/29
=> chore(deps): pin 'google-crc32c < 0.2dev'

google/resumable_media/_helpers.py, setup.py
Uses the new namespaced-version of the library.
Release-As: 1.0.0
=> feat: bump 'google-crc32c >= 1.0'

google/resumable_media/_helpers.py, tests/unit/test__helpers.py
The current checksum logic only allowed checksum headers in the format `crc32c=hash1,md5=hash2`, but GCP may actually return them with a space in-between as `crc32c=hash1, md5=hash2`.
This means that checksums are not being verified correctly for any header response like the latter.
If you want an actual example of a response from GCP that demonstrates this, here's one:
```
{
"X-GUploader-UploadID":"REDACTED",
"Expires":"Tue, 08 Sep 2020 21:27:47 GMT",
"Date":"Tue, 08 Sep 2020 21:27:47 GMT",
"Cache-Control":"private, max-age=0",
"Last-Modified":"Tue, 08 Sep 2020 21:27:47 GMT",
"ETag":"REDACTED",
"x-goog-generation": "REDACTED",
"x-goog-metageneration":"1",
"x-goog-stored-content-encoding":"identity",
"x-goog-stored-content-length":"1043237",
"Content-Type":"application/octet-stream", …
```
=> fix: allow space between checksums in header

google/async_resumable_media/requests/_request_helpers.py, noxfile.py, setup.py, tests_async/system/requests/conftest.py, tests_async/system/requests/test_download.py, tests_async/unit/test__download.py
move google.auth.default_async, aiohttp_requests use to google.auth._default_async, _aiohttp_requests
=> chore(deps): use google-auth >= 1.22.0, 2.0dev which includes google.auth.default_async, aiohttp_requests
